### PR TITLE
Fix resolving re-defined with factory dependencies

### PR DESCRIPTION
**Pull request by viktorprogger**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Tests pass?   | ❌
| Fixed issues  | ❌

This PR potentially replaces [another one](https://github.com/yiisoft/factory/pull/5).

### CODE REVIEW

**Comment by viktorprogger** [comment]
This PR potentially replaces [another one](https://github.com/yiisoft/factory/pull/5) in this repo and [one more](https://github.com/yiisoft/di/pull/100) in `yiisoft/di`.

**Comment by yiiliveext** [comment]
Tests: 26, Assertions: 61, Errors: 2, Failures: 5.

**Comment by viktorprogger** [comment]
@yiiliveext, yes, I know it. See issue #6.

**Comment by yiiliveext** [comment]
> @yiiliveext, yes, I know it. It is not related to this PR. See issue #6.

See my alternative PR (https://github.com/yiisoft/factory/pull/8).
It passes your test.

**Comment by viktorprogger** [comment]
Maybe #8 is event better than this PR because it allows to check not only explicitly set definitions.

So, as conclusion I can say that there is really no need to use `CompositeContainer`.

**Comment by yiiliveext** [comment]
> Maybe #8 is event better than this PR because it allows to check not only explicitly set definitions.

I agree. On my PR all tests have been passing.
 
> So, as conclusion I can say that there is really no need to use `CompositeContainer`.

I agree you are right.

**Pull request closed without merging**
